src/options.js, test/fixtures/oid-feature.json, test/to-esri.js
should fix issue when querying only one oid
accidentally added redundant 'adding an object id' test function (which has been removed)
=> Fix existing oid

src/where.js, test/filter.js
Currently without the IS command the property will not get nested under the properties =>.
This means IS NULL and IS NOT NULL do not work.
=> fix: adds IS command for null searching

src/where.js, test/filter.js
We noticed sometimes that AGOL would send 1=1 at the end of a query string with many other query parameters.  When this would happen the field from 1=1 would get converted to properties => 1 and break the query.
=> fix: covers case where AGOL sends appended 1=1 along with other query fields

package.json, src/where.js, test/prepare.js
This PR will parse the input WHERE clause into AST, instead of doing regex matching, and traverse the tree to generate translated clause. Not many comments are added since the implementation is very straightforwards. No regex hack :-)
From what I can tell from the test running, the speed is the same.
This PR has covered the problem at #53.
=> Feature / Use AST to translate WHERE clause

src/options/index.js, src/options/normalizeOptions.js, src/options/normalizeSQL.js
Discovered that date fields were being add to response payloads even in cases where said date fields were excluded by use of the `outFields` query parameter.  This caused unwanted drawing/rendering effects in ArcGIS Pro.
Also discovered that `outFields` arriving as a comma delimited string were not being parsed properly in Winnow queries.
This PR includes a fix to parse the `outFields` input if comma-delimited, and additional checks to include date fields in response payloads only when specifically requested with `outFields` query param (or when `outFields=*`).
=> Prevent date fields from being add to response when not requested

src/sql.js, test/filter.js, test/fixtures/missing-geometry.json
Check for `feature === null` on `ST_Intersects` function.  Null feature can be passed if a source feature has a `geometry === null`.
=> Add null feature check to ST_Intersects

CHANGELOG.md, package.json, src/executeQuery.js, test/to-esri.js
If a provider's metadata `idField` is not set, create value of OBJECTID from a numeric hash of the raw feature.
=> Create OBJECTID by hashing raw feature.

CHANGELOG.md, package.json, src/geometry/transform-array.js, src/options/normalizeOptions.js, src/sql.js, test/filter.js
Add support for esriSpatialRelEnvelopeIntersects (aka, ST_EnvelopeIntersects) and companion test. Upgrade to  turf/bbox-polygon to ^6.0.1.
=> Add support for esriSpatialRelEnvelopeIntersects

package.json, src/executeQuery.js, src/geometry/utils.js, src/select/fields.js, src/where.js
Discovered `standard` was not scanning files properly on `npm test`.  Specifically,  `standard src` was not picking up style errors in files of the `src` directory.  When `standard` was run without `src` a number of style issues were reported.  Those style issues were also fixed in this commit.
=> Have standard.js scan files on npm test

package.json, src/options/index.js, src/options/normalizeOptions.js, test/normalizeOptions.js
AGOL issues some queries that send `inSR` as an object with properties `wkid` and or `latestWkid`.  The current `normalizeInSR` function did not expect or handle an object data-type, rather, it expects a string or integer. On receiving an object, in would return a string `EPSG: [Object object]`, causing the request to fail.  Issue reported [here](https://github.com/koopjs/koop-output-geoservices/issues/5).
- Wrote tests to cover functionality of pre-refactor `normalizeInSR`
- Refactored `normalizedInSR`
- Take spatial reference from `geometry` object if it is defined, as the `inSR` is primarily used to reproject the input geometry to wkid 4326.  
- Look for and parse `object` type for `inSR`
- Validate spatial reference code.  If invalid, warn and default to 4326
- Add additional tests to …
=> Handle inSR options that arrive as objects.

CHANGELOG.md, package.json, src/geometry/project-coordinates.js, src/options/index.js, src/options/normalizeOptions.js, src/sql.js, test/filter.js, test/fixtures/street-trees-102645.json, test/normalizeOptions.js, test/prepare.js, test/project-coordinates.js
This PR enables filtering by geometry on data that is not necessarily in SRS WGS84 (prior to this modification, source data was assumed to be WGS84).  I have added a new option named `sourceDataSR` which informs winnow that source data that is in a non-WGS84 SRS.  Using this SRS, the geometry envelop can be projected correctly so that in matches the source data.
Unless the source data SRS is one of handful of SRSs that proj4 stores in its hash, the SRS must be passed along to proj4 as WKT.  Thus the PR includes some refactoring on functions that normalize incoming SRSs.
Added tests.
=> Filter non wgs84 source data

CHANGELOG.md, src/executeQuery.js, src/index.js, src/options/index.js, src/options/normalizeOptions.js, src/options/normalizeSQL.js, src/query.js, src/select/fields.js, src/sql.js, test/filter.js, test/limit.js, test/order.js, test/to-esri.js
Currently, standard and limit queries have SQL applied to raw data set feature by feature.  This facilitates the application of the `esriFy` function (it needs the full geometry and property set), but means that ordering, limit and offset functionality are completed post-SQL query as well.  This complicates ordered paging, because an iterative sort is required on the full feature set, prior to applying the limit and offset.
As an alternative, I moved the `esriFy` into the SQL execution.  This allows the SQL to be applied to the full feature set, and which allows the leveraging of the SQL for ORDER BY, LIMIT and OFFSET.
~The only downside I discovered was in calculation of the `limitExceeded` property.   For queries that include both a `limit` and a `where`, it's not possible to discern …
=> Move esriFy, ordering, limit, and offset functionality to ala-sql.

package.json, src/executeQuery.js, test/to-esri.js
Hi there, I am trying to build a version of Koop in an environment where I am not able to compile native node modules, this means I can't use the most up-to-date version of Koop due to winnow's dependency on farmhash.
This PR makes the native farmhash module optional, adding a fallback to a pure JavaScript hashing library when farmhash is not installed. This means those that cannot or don't want to use native modules can still use winnow, while others can still take advantage of farmhash's superior speed.
I roughly followed the instructions for optional dependencies on [npm](https://docs.npmjs.com/files/package.json#optionaldependencies) but let me know if you'd rather I implemented it in a different way.
Thanks!
=> Change farmhash to an optional dependency and add fall back to string-hash

src/options/normalizeSQL.js
This PR splits incoming `orderByFields` parameter by `,` if it is a string.  Before now, the string was simply being placed in the first item of the array.  This may have worked when ordering was being done post-alasql, but now it is incompatible.
=> Handle comma delimited orderByFields.

CHANGELOG.md, src/options/index.js, src/options/normalizeOptions.js, src/options/normalizeSQL.js, src/sql.js, test/normalizeOptions.js, test/normalizeSQL.js, test/options.js, test/to-esri.js
This PR removes a workaround (implemented 5 or 6 months ago) that helped get koop working on ArcGIS clients.  The workaround added an`OBJECTID` field to payloads even if a provider had set `idField` in the provider metadata.  The result was two properties with the same value. This is not ideal, for reasons noted in https://github.com/koopjs/FeatureServer/issues/127.
I've identified the original bug - it was in queries that had `returnIdsOnly=true`.  When that parameter was set, `outFields` were forced to `OBJECTID` even if `idField` had been set in the provider.  That bug is fixed and the workaround is not removed.  If `idField` is set a duplicate property `OBJECTID` is no longer added.
I've added some test coverage for the normalization functions that were added or modified.
NOTE: there …
=> Fix payloads when idField is set

CHANGELOG.md, src/sql.js, src/where.js, test/where.js
The PR addresses a deficiency in current code base that prevents ability to query on OBJECTID in the `where` parameter when OBJECTIDs are generated on-the-fly in Winnow.
**Context:**
If data arrives in winnow _without_ an OBJECTID field and no alternative assignment using the `metadata.idField` property, then winnow generates an OBJECTID on-the-fly in a user-defined `SELECT` function that is passed into alasql.  However, problems occur if the `where` parameter queries OBJECTID, e.g., `where=OBJECTID=1234`, because the OBJECTID does not yet exist on the data when the alasql `WHERE` does its filtering.  Thus, no features are ever returned.
**Solution:**
If the WHERE includes predicates with OBJECTID, but no OBJECTID is defined on the data, and no `idField` has been assigned, we have to use …
=> Handle where queries on OBJECTID when OBJECTID is generated on the fly

CHANGELOG.md, src/sql.js, test/filter.js, test/sql.spec.js
I put the `ST_Within` function (our custom function that gets added to alasql) under direct test and found it was not functioning as expected.  It was suppose to check if a feature was completely within a target geometry (the geometry filter). But it was checking the opposite - if a filter was within a feature.
This PR fixes and demonstrates with tests.
=> Fix and test ST_Within.

CHANGELOG.md, src/groupBy.js, src/query.js, src/select/aggregates.js, test/aggregate.js
The SQL query created when using a GROUP BY with a
WHERE clause was invalid, the GROUP BY was before
the WHERE clause. This resulted in alasql failing
to parse the query.
Fixed to separate adding the GROUP BY fields in the
SELECT clause, and adding the actual GROUP BY clause
later after the WHERE clause.
Added unit test to cover the changes.
Before the change, the generate SQL query looked like
this:
SELECT AVG(properties->`Trunk_Diameter`) as `avg_Trunk_Diameter`,
properties->`Genus` as `Genus`
FROM ?
GROUP BY  properties->`Genus`
WHERE properties->`Trunk_Diameter` > 10
After it looks like this:
SELECT AVG(properties->`Trunk_Diameter`) as `avg_Trunk_Diameter`,
properties->`Genus` as `Genus`
FROM ?
WHERE properties->`Trunk_Diameter` > 10
GROUP BY  properties->`Genus`
=> Fix group by with where clause.

CHANGELOG.md, src/options/normalizeSQL.js, test/aggregate.js
ArcGIS Operations Dashboard allows you to create a Serial Chart,
grouping the data one field, and splitting the bars by a second. The
queries it sends to the feature service are comma separated. This was
being treated by winnow as a single field name containing a comma,
instead of splitting the parameter into a list of field names.
Updated the normalizeGroupBy function to split the parameter with the
comma character. (I've done this for both 'groupBy' and
'groupByFieldsForStatistics', could maybe restrict it to only do it for
the Esri 'groupByFieldsForStatistics' property?)
Added unit test to cover it.
=> Split groupByFieldsForStatistics by comma

.travis.yml
Travis builds are failing on the test command with node < 10.  However, tests pass outside Travis environment with node 8, so this seems unique to Travis environment.  Bumping node travis uses to 10.
=> Bump travis node to 10.

CHANGELOG.md, package-lock.json, package.json, src/sql.js
hi @rgwozdz! 👋 
this PR replaces the dependency on terraformer with the primitive-less ES module i published as [`@terraformer/spatial`](https://www.npmjs.com/package/@terraformer/spatial).
its not necessary by a long shot, but if you're interested in the context the conversation started way back [in 2016](https://github.com/Esri/terraformer/issues/268).
if you'd like me to remove the package-lock.json from this PR, just say the word. i saw some koopjs repos that had one so i thought it _might_ actually be helpful. 🤷
=> update to latest terraformer package

lib/normalize-query-options/date-fields.js, lib/normalize-query-options/index.js, lib/normalize-query-options/normalizeOptions.js, test/normalize-query-options/date-fields.spec.js, test/normalize-query-options/normalizeOptions.js
Move into it's own file and create a full set of tests. Removed "normalize" from function name, as this function doesn't "normalize" anything - instead it derives an array of dateFields from other options.
=> Refactor date-fields query option.

lib/sql-query-builder/index.js, lib/sql-query-builder/where.js, test/integration/filter.spec.js, test/unit/sql-query-builder/where.spec.js
Specifically refactors portion of where-clause generation that handles OBJECTID predicates.  Just cleans up code, does not change functionality. Some background: 
1. If a dataset is flagged for translation to Esri JSON and doesn't have metadata that defines an `idField`, Winnow will add an OBJECTID field to each feature's attributes and give it a value based on hashing of the feature.
2. Follow-up queries by the client may include where-clause predicates that include the OBJECTID.  Since the dataset doesn't actually have an OBJECTID field, we need to hash each feature on the fly as the where predicate executes so that we have an OBJECTID to make the comparison.
3.  We do this by replacing the where-clause predicate that targets OBJECTID with an inline function that will make the …
=> Clean up where-clause generation

CHANGELOG.md, lib/alasql.js
On heroku, queries were broken by farmhash's binary not loading correctly and the try catch not finding it.
I added a line to test farmhash and on systems where the issue exists, it should instead use the other hashing algo, which works correctly.
=> Queries on heroku were broken

lib/geometry/index.js, lib/sql-query-builder/index.js, lib/sql-query-builder/where/geometry-predicate.js, lib/sql-query-builder/where/index.js, lib/sql-query-builder/where/translate-sql-where.js, test/unit/sql-query-builder/where/geometry-predicate.spec.js, test/unit/sql-query-builder/where/index.spec.js, test/unit/sql-query-builder/where/translate-sql-where.spec.js
The geometry filter is part of the final where-clause.  As such, this PR reorganizes files, and consolidates the translation of the where and geometry options, which cleans up the higher level SQL generation function.  Unit tests added.
=> Consolidate where-clause generation.

CHANGELOG.md, lib/sql-query-builder/where/translate-sql-where.js, test/integration/filter.spec.js, test/integration/fixtures/trees.json
ArcGIS clients escape single quotes in where clauses with sql-style `''`.  But this double single quote breaks filtering because the SQL parser doesn't handle `''`.  To fix this until we can get a PR into flora-sql-parser, this PR implements:
1. Replace any `''` found in the `where` with a `\'` which is the escape used by flora-sql-parser. Example:
`where=food='bar''s'` becomes `where=food='bar\'s'`
After parsing the `where` with flora-sql-parser, value of this node of the AST is `bar's`.  Note that parsing removes the escape from the single quote!
This result is problematic for winnow because we wrap values in single quotes to prepare them for the alasql query statement.  So the query statement ends up looking like `SELECT * FROM WHERE food = 'bar's'`.  This breaks the alasql query …
=> Handle escaped single quotes in where parameter

CHANGELOG.md, lib/normalize-query-options/helpers/get-collection-crs.js, lib/normalize-query-options/helpers/index.js, lib/normalize-query-options/output-data-spatial-reference.js, lib/normalize-query-options/source-data-spatial-reference.js, test/unit/normalize-query-options/helpers/get-collection-crs.spec.js, test/unit/normalize-query-options/output-data-spatial-reference.spec.js
When no reprojection, output CRS should be assigned same value as input CRS.  If neither `inputCrs` or `sourceSR` options are defined, Winnow should look for a CRS definition on the collection.
=> Output CRS deference fix.

CHANGELOG.md, lib/calculate-class-breaks/filter-and-validate-classification-features.js, lib/calculate-class-breaks/index.js, lib/calculate-class-breaks/normalize-classification-values.js, test/unit/calculate-class-breaks/filter-and-validate-classification-features.spec.js
The refactor for class break generation had a few breaking changes:
* Classification fields that are stringified numbers should not be rejected; rather, they should be cast to numbers
* Log normalization function that produces values < 0 should return `0`.
Note that I don't necessarily agree with the logic here, just maintaining the legacy code so we don't introduce a breaking change.  This logic should be revisited and perhaps changed - it may make more sense to move class break generation out of winnow and into FeatureServer as this seems like code that is specifically for the generateRenderer route.
=> Fix breaking change

CHANGELOG.md, lib/normalize-query-options/geometry-filter-spatial-reference.js
There was a faulty check in the geometry filter normalizer that was causes a warning to always get printed.
=> Fix check for warning log.

CHANGELOG.md, lib/normalize-query-options/geometry-filter.js, test/integration/filter.spec.js, test/unit/normalize-query-options/geometry-filter.spec.js
Adds support for the `geometry` query param to be Point coordinates as specified by the `esriGeometryPoint` `geometryType` https://developers.arcgis.com/rest/services-reference/enterprise/query-feature-service-layer-.htm
This prevents an error in koop when using geoservices output for a link like:
https://featureserver.com/provider/id/FeatureServer/0/query?f=json&geometryType=esriGeometryPoint&geometry=7652714.335571289%2C-1985856.184782909&geometryType=esriGeometryPoint&inSR=102100&outSR=102100
Added tests for this case, and monkey patched our version of koop to verify the fix works in our case.
Resolves https://github.com/koopjs/winnow/issues/203
=> Add support for point geometry

CHANGELOG.md, lib/sql-query-builder/create-sql-params.js, lib/sql-query-builder/create-sql-string.js, lib/sql-query-builder/index.js, test/unit/sql-query-builder/create-sql-params.spec.js, test/unit/sql-query-builder/create-sql-string.spec.js
When `returnGeometry=false`, the generated SQL doesn't include call to reprojection function; As a result we should not add CRS arguments to the array of sql parameters.
=> Patch sql param generation

CHANGELOG.md, lib/normalize-query-options/spatial-reference.js, test/unit/normalize-query-options/spatial-reference.spec.js
Spatial reference option currently fails validation if additional, but unused, properties are included.  This fixes https://github.com/koopjs/winnow/issues/191.
=> Allow optional properties on incoming spatial reference.

CHANGELOG.md, lib/filter-and-transform/transforms/to-esri-attributes.js, test/unit/filter-and-transform/transforms/to-esri-attributes.spec.js
The transform-to-esri feature should stringify any nested GeoJSON properties. This is confirmed by looking at responses from AGO services. So something like:
```js
"nested": {
"foo": "bar"
}
```
should become:
```js
"nested": "{\"foo\":\"bar\"}"
```
=> F/serialize nested properties when converting to Esri JSON

CHANGELOG.md, lib/sql-query-builder/select/index.js, test/unit/sql-query-builder/select/index.spec.js
This PR adds support for queries with the `DISTINCT` operator.   Note this is the same change as https://github.com/koopjs/koop/pull/467, but ported here for users of the deprecated library.
=> Add support for DISTINCT
